version: '3'
services:
  user-service:
    build: ./user-service
    ports:
      - '3001:3001'
    env_file:
      - ./user-service/.env

  question-service:
    build: ./question-service
    ports:
      - '5000:5000'
    env_file:
      - ./question-service/.env.local

  collaboration-service:
    build: ./collaboration-service
    ports:
      - '5555:5555'

  matching-service:
    build: ./matching-service
    ports:
      - '5001:5001'
    env_file:
      - ./matching-service/.production.env

  ai-service:
    build: ./ai-service
    ports:
      - '4444:4444'
    env_file:
      - ./ai-service/.env.local
